### ISSUE TITLE
Help dialog

### ISSUE THREAD

**Issue by rendom** [fulhax/ncpamixer#10]
Suggestion: ? key should open a help dialog, listing the keyboard shortcuts. [ncdu](https://dev.yorhel.nl/ncdu) behaves this way.

https://www.reddit.com/r/linux/comments/4y1xr8/ncpamixer_cli_alternative_to_pavucontrol/d6ranna

**Comment by c0r73x** [comment]
We should probably add a manpage as well :beer:

**Comment by bytting** [comment]
Exactly what I was thinking. This would have been nice
