### ISSUE TITLE
Exiting with 1

### ISSUE THREAD

**Issue by livibetter** [fulhax/ncpamixer#12]
My shell prompt has exit status displayed, so I noticed ncpamixer always exits with 1, the following is gdb output using 1af8464:

```
$ make debug
<snip>
$ gdb build/ncpamixer
GNU gdb (Gentoo 7.6.2 p1) 7.6.2
<snip>
(gdb) r
<snip>
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff32c0700 (LWP 17377)]
<Q key pressed>
[Thread 0x7ffff7fca780 (LWP 17373) exited]
[Inferior 1 (process 17373) exited with code 01]
```

Some versions information:

* GCC 4.9.3
* PulseAudio 8.0
* `/lib64/libpthread-2.22.so`

----

2016-12-30T11:42:17Z: added a list of versions

**Comment by FredrikHson** [comment]
seems like the exit(1) comes from 
https://github.com/fulhax/ncpamixer/blob/master/src/pa.cpp#L809

**Comment by c0r73x** [comment]
@rendom shouldn't it try to recreate context or wait for pulse if the context gets destroyed? exit, seems like a hacky fix :P

**Comment by livibetter** [comment]
I am not a C++ coder and have zero experience with PulseAudio, but from what I understand, the `pa_context_disconnect` would set `PA_CONTEXT_TERMINATED` state and the callback is called.

I did a quick `grep` on PulseAudio source, `PA_CONTEXT_TERMINATED` can only be set by `pa_context_disconnect`. So, I think it's safe to just remove that `exit`, because when `PA_CONTEXT_TERMINATED` state comes in, it's because the program wants to disconnect, it's not caused by any errors.

Of course, there could be a failure to proper disconnection, so if really want to be thorough, the callback could set, say `pa_init` to `false`, then checking it after disconnecting call. If it's not clean termination, then exit with error. But I would say, that's quite unnecessary since I don't think there is a slight chance that termination would fail.

**Comment by c0r73x** [comment]
Fixed in dev.
