### ISSUE TITLE
Can't find curses when compiling

### ISSUE THREAD

**Issue by avindra** [fulhax/ncpamixer#14]
This should be a pretty straightforward `.spec` file:

https://build.opensuse.org/package/view_file/home:avindra/ncpamixer/ncpamixer.spec?expand=1

The full log is [here for 32 bit](https://build.opensuse.org/package/live_build_log/home:avindra/ncpamixer/openSUSE_Tumbleweed/i586) and [here for 64 bit](https://build.opensuse.org/package/live_build_log/home:avindra/ncpamixer/openSUSE_Tumbleweed/x86_64) (same error in both), but the relevant lines are:

```
...

[   51s] [ 63%] Building CXX object CMakeFiles/ncpamixer.dir/ui/tabs/playback.cpp.o
[   51s] [ 68%] Building CXX object CMakeFiles/ncpamixer.dir/ui/tabs/recording.cpp.o
[   51s] /home/abuild/rpmbuild/BUILD/ncpamixer-1.2/src/ui/tab.cpp:5:10: fatal error: menu.h: No such file or directory
[   51s]  #include <menu.h>
[   51s]           ^~~~~~~~
[   51s] compilation terminated.
[   51s] make[4]: *** [CMakeFiles/ncpamixer.dir/build.make:303: CMakeFiles/ncpamixer.dir/ui/tab.cpp.o] Error 1
[   51s] make[4]: *** Waiting for unfinished jobs....
[   52s] make[3]: *** [CMakeFiles/Makefile2:100: CMakeFiles/ncpamixer.dir/all] Error 2
[   52s] make[2]: *** [Makefile:130: all] Error 2
[   52s] make[1]: *** [Makefile:26: build] Error 2
[   52s] make: *** [Makefile:48: release] Error 2
[   52s] error: Bad exit status from /var/tmp/rpm-tmp.K0uceo (%build)
```

Any insight as to how `menu.h` would be missing?

**Comment by rendom** [comment]
My old spec file https://build.opensuse.org/package/view_file/home:r3ndom/ncpamixer/ncpamixer.spec?expand=1

**Comment by avindra** [comment]
^ @rendom's spec file, which is targeting ncpamixer 1.1 builds cleanly for RHEL 7 fwiw.
