### ISSUE TITLE
Segmentation fault (SIGSEGV)

### ISSUE THREAD

**Issue by monofox** [fulhax/ncpamixer#15]
System:
Gentoo, Linux Kernel 4.13.8-ck
sys-libs/ncurses-6.0-r1
media-sound/pulseaudio-11.1
Firefox 57.0 (64-bit)

When scrolling/seeking much in a video, ncpamixer is crashing after some time with SIGSEGV, Segmentation fault.

    Thread 1 "ncpamixer" received signal SIGSEGV, Segmentation fault.
    0x00007fffec0206a0 in ?? ()

Stacktrace:

    (gdb) bt
    #0  0x00007fffec0206a0 in ?? ()
    #1  0x000000000042b12a in Tab::draw (this=0x739600) at /tmp/ncpamixer/src/ui/tab.cpp:103
    #2  0x000000000042a84b in Ui::draw (this=0x63dca0 <ui>) at /tmp/ncpamixer/src/ui/ui.cpp:329
    #3  0x000000000042a89d in Ui::run (this=0x63dca0 <ui>) at /tmp/ncpamixer/src/ui/ui.cpp:339
    #4  0x000000000041ec60 in main (argc=1, argv=0x7fffffffdcc8) at /tmp/ncpamixer/src/pulsemixer.cpp:87

Problem reproducible with any video, also from youtube. Everytime when you seek in the video, the input stream from e.g. firefox is disappearing and shortly after that (when again played), the stream appears again. 

Edit 11:08 UTC: 
SIGSEGV is produced by accessing: 
`i.second->getRelation()`

Attached core dump.

If more details are necessary, let me know.

**Comment by monofox** [comment]
Promised core dump:
[core.7369.gz](https://github.com/fulhax/ncpamixer/files/1565574/core.7369.gz)

**Comment by FredrikHson** [comment]
managed to replicate this.
seems to be that i.second is used after deleting it in another thread

**Comment by c0r73x** [comment]
@FredrikHson this is the same as #21 ?
