### ISSUE TITLE
[Request] Distracting free static view

### ISSUE THREAD

**Issue by Hund** [fulhax/ncpamixer#18]
It would be nice with a toggable static view that's not distracting when you leave it open. Like this:

![ncpamixer_static](https://user-images.githubusercontent.com/320498/48790118-edc0b080-ecee-11e8-9383-9725cfd6c609.png)

**Comment by c0r73x** [comment]
Without the bars updating you meen? We can add that.

**Comment by c0r73x** [comment]
Added in 732a3c6ebfbd6d3307e6f947b2d9f3d0373ed1f0 with both key event "toggle_static" and default mode for theme with boolean value "theme.[themename].static_bar"

**Comment by Hund** [comment]
Thanks! :)
