### ISSUE TITLE
UI issue on Ubuntu Bionic

### ISSUE THREAD

**Issue by clangen** [fulhax/ncpamixer#25]
First off, really cool project!

It works very well on my Arch install, but seems to have character-drawing problems on Ubuntu. Maybe specific to my setup, but I spent a few minutes looking at the code and my environment and didn't see anything obviously wrong.

Here's what I see shelled into my Ubuntu machine:

![image](https://user-images.githubusercontent.com/2031666/51966698-0998af00-2422-11e9-9dce-7cfaffda1126.png)

Output from `locale` seems reasonable:

```
➜ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I also thought maybe it was some sort of Unicode character drawing issue, but I tried another terminal-based app and it seems to be rendering extended (non-Latin, UTF8) characters just fine.

For reference, here's what it looks like when I'm shelled into my Arch install:

![image](https://user-images.githubusercontent.com/2031666/51966770-495f9680-2422-11e9-9439-1523a49d832e.png)

**Comment by c0r73x** [comment]
This is because it uses ncurses without widecharacter support on Ubuntu,
you can try to build it using `make distclean` then `USE_WIDE=1 make` this
works on some distros. Not sure it will work on Ubuntu though.

**Comment by clangen** [comment]
Yep, that fixed it. Thanks! :)

**Comment by Hund** [comment]
Let me know if I should create a separate issue for this. I have the same issue on Gentoo with your ebuild[1] and the flag `wide`. What to do?

1: https://github.com/fulhax/fulhax-overlay/blob/master/media-sound/ncpamixer/ncpamixer-1.3.3.ebuild

**Comment by c0r73x** [comment]
Humm, heat kind of issue? I think I installed with that ebuild. I might
have forgotten to push something though. 🤔

**Comment by Hund** [comment]
This. :/

![2019-02-10-010725_508x148_scrot](https://user-images.githubusercontent.com/320498/52527877-48572080-2cd0-11e9-83a4-501eaccf8d9e.png)

**Comment by c0r73x** [comment]
Humm, that is odd. I even added the wide flag as default. I will check if I
pushed everything.

**Comment by c0r73x** [comment]
Ah, ok.. it seems i run the 9999 version with the wide flag on. Probably the 3.3.3 tag is incorrect.

**Comment by zethnest** [comment]
I am still having the issue of terminal not showing correctly after running `USE_WIDE=1 make` instead of just `make`.

I seem to have no issue of displaying the character since it shows the character perfectly fine in Vim. 
Can you help me trace down the issue?

System: Debian 9.7.0
Terminal: st

**Comment by c0r73x** [comment]
Did you run `make distclean` before running `USE_WIDE=1 make`?

**Comment by zethnest** [comment]
Yes, I have run `make distclean` to clean the build beforehand.

**Comment by c0r73x** [comment]
Did you clone from master, or is it the 1.3.3 file?

**Comment by zethnest** [comment]
I cloned it from the master

**Comment by c0r73x** [comment]
I will have to set up a vm with debian when I get home to do some testing, seems it refuses to use ncursesw for some strange reason :(

**Comment by zethnest** [comment]
I appreciate your help

**Comment by hamsterready** [comment]
Install these:

```
sudo apt-get install libncursesw6 lib64ncursesw6
```

and when you build with `USE_WIDE=1` look for something like this:

```
-- Looking for wsyncup in /usr/lib/x86_64-linux-gnu/libcurses.so
-- Looking for wsyncup in /usr/lib/x86_64-linux-gnu/libcurses.so - found
-- Looking for cbreak in /usr/lib/x86_64-linux-gnu/libncursesw.so
-- Looking for cbreak in /usr/lib/x86_64-linux-gnu/libncursesw.so - found
```

Worked for me.

**Comment by Hund** [comment]
Any news on this? :)

**Comment by c0r73x** [comment]
Hi, I've been quite busy and havn't got time to check on this. But from @hamsterready 's comment it seems that Ubuntu don't shipt with ncursesw by default?

**Comment by Tonus1** [comment]
Hi,
Same problem here on Slackware64-current.

```
ls /usr/include/ncursesw/
total 380K
-rw-r--r-- 1 root root  98K janv.  1 05:21 curses.h
-rw-r--r-- 1 root root 6,7K janv.  1 05:21 cursesapp.h
-rw-r--r-- 1 root root  28K janv.  1 05:21 cursesf.h
-rw-r--r-- 1 root root  20K janv.  1 05:21 cursesm.h
-rw-r--r-- 1 root root 8,5K janv.  1 05:21 cursesp.h
-rw-r--r-- 1 root root  49K janv.  1 05:21 cursesw.h
-rw-r--r-- 1 root root 7,2K janv.  1 05:21 cursslk.h
-rw-r--r-- 1 root root 2,9K janv.  1 05:21 eti.h
-rw-r--r-- 1 root root 9,5K janv.  1 05:21 etip.h
-rw-r--r-- 1 root root  19K janv.  1 05:21 form.h
-rw-r--r-- 1 root root  12K janv.  1 05:21 menu.h
-rw-r--r-- 1 root root 4,1K janv.  1 05:21 nc_tparm.h
lrwxrwxrwx 1 root root    8 janv.  8 23:00 ncurses.h -> curses.h
-rw-r--r-- 1 root root 4,4K janv.  1 05:21 ncurses_dll.h
-rw-r--r-- 1 root root 4,1K janv.  1 05:21 panel.h
-rw-r--r-- 1 root root  41K janv.  1 05:21 term.h
-rw-r--r-- 1 root root 8,9K janv.  1 05:21 term_entry.h
-rw-r--r-- 1 root root 3,4K janv.  1 05:21 termcap.h
-rw-r--r-- 1 root root  15K janv.  1 05:21 tic.h
-rw-r--r-- 1 root root 3,1K janv.  1 05:21 unctrl.h
```

Tried to add :
`-DWITH_UNICODE=1`
`-DNCURSESW_H_INCLUDE="ncursesw/ncurses.h"`
With no luck.
