### ISSUE TITLE
Allow user to select input/output device

### ISSUE THREAD

**Issue by pengux** [fulhax/ncpamixer#31]
Maybe I missed something but I can't find a keybinding to select a input/output source. I had to run the commands:

```
pacmd list-sink-inputs
pacmd move-sink-input [input index] [sink index]
```

to switch between different output devices for example.

**Comment by c0r73x** [comment]
| switch | tab | Cycle trought sinks, outputs, profile and ports |

| dropdown | c | Open dropdown for selecting sinks, outputs, profile and ports |

Any of these should work?

**Comment by pengux** [comment]
Here is a screenshot:

![image](https://user-images.githubusercontent.com/2286687/68851167-ad172f80-06d5-11ea-995f-37fd218f51cb.png)

In this example, the input is redirected to the selected sink `Built-in Audio...`, but how can I select the `Dell Universal Dock...` as the the output sink?

**Comment by c0r73x** [comment]
Aha it’s d, for set_default

tors 14 nov. 2019 kl. 11:56 skrev Peter Nguyen <notifications@github.com>:

**Comment by pengux** [comment]
Thanks, didn't realized that `set_default` would set the actual sink to be used.
