### ISSUE TITLE
Glyphs not rendering correctly

### ISSUE THREAD

**Issue by scrouthtv** [fulhax/ncpamixer#32]
![image](https://user-images.githubusercontent.com/23227405/72802546-53d6f980-3c4c-11ea-9023-056dd23480c5.png)

I'm running `Linux archlinux 5.4.13-arch1-1 #1 SMP PREEMPT Fri, 17 Jan 2020 23:09:54 +0000 x86_64 GNU/Linux` and
```
ncpamixer v1.3
Build type: release
Build date: 2020-01-20 16:59
```
The three fonts shown are `Monofur`, `Monaco` and `Hermit`. As you can see, instead of the little symbol(![image](https://user-images.githubusercontent.com/23227405/72802768-c942ca00-3c4c-11ea-8b33-88f8a396c87b.png)) the ~Y is displayed. Also the slider is not displayed as it should be, but instead there is a ~V~H:
![image](https://user-images.githubusercontent.com/23227405/72802848-fd1def80-3c4c-11ea-9551-0c0b65cc4227.png)

With some other fonts the glyphs are rendered correctly, but since Hermit is the one I mainly use I'd like to know whether it's possible to fix this in some way?

**Comment by c0r73x** [comment]
Humm strange, could you try to compile it with USE_WIDE=1 ?

**Comment by scrouthtv** [comment]
I didn't compile it myself, but installed the AUR version. I guess you want me to append the `USE_WIDE=1` to the `make` command line. The issue persists:
![image](https://user-images.githubusercontent.com/23227405/72878591-812eb080-3cfb-11ea-8d95-09467a6df1d9.png)
What I did:
```
 $ make USE_WIDE=1
 $ build/ncpamixer --version
ncpamixer git v1.3.3-1-g158dc0d
Build type: release
Build date: 2020-01-22 09:40
```

**Comment by FredrikHson** [comment]
got similar results myself if i launched with: LANG=C ./build/ncpamixer

**Comment by c0r73x** [comment]
That would make sense i guess, you probably want to run utf-8 🤔

**Comment by scrouthtv** [comment]
Oh well. Didn't know. When launching with LANG=en_US.UTF-8 it works..

**Comment by scrouthtv** [comment]
Can someone help me on how I can fix this?
```
# cat /etc/locale.conf
LANG=en_US.UTF-8
# localectl
System Locale: LANG=en_US.UTF-8
echo $LANG
C
```
I even have a line `export LANG=en_US.UTF-8` in my zshrc but the lang is still `C`.

**Comment by c0r73x** [comment]
Humm did you forget to run locale-gen maybe?

**Comment by scrouthtv** [comment]
I (re-) ran `locale-gen`, the output said there already was some file for `en_US.UTF-8`.

After testing my problem I set the language using `localectl` which didn't apply instantly, but **after a reboot everything is working fine** I guess I never really set the language or this one boot was broken. (Or could a kernel upgrade possibly break this? They tend to break a lot of things for me)

**Comment by urbanprah** [comment]
setting LC_ALL worked for me

**Comment by OrionRandD** [comment]
- I've also had these glyphs issues...
- In my GNU/Debian (Sid) 
- Siduction distro
- https://siduction.org/

- But, fortunately, this worked for me (using sudo)
- cd ncpamixer 
- sudo distclean
- sudo USE_WIDE=1 make
- sudo USE_WIDE=1 make install
- Then, I moved the config file to:
- tree .config/ncpamixer
- ~/.config/ncpamixer
- └── ncpamixer.conf

- I know that this is an old issue, but, perhaps,
- could be of any help to someone...
