### ISSUE TITLE
gcc8 compiler

### ISSUE THREAD

**Issue by SiNick1** [fulhax/ncpamixer#37]
in file pa.cpp change line 466 to:

`strncpy(p->app_name, app_name, sizeof(p->app_name) -1);`  to make compile and install

**Comment by bytting** [comment]
With warnings treated as errors, this line breaks the build. p->app_name is initialized in the constructor so this seems to be the appropriate fix, assuming pulseaudio returns a max 255 null terminated string in app_name

**Comment by c0r73x** [comment]
I would suspect that pulseaudio has a define for max appname, better to use that one.
