### ISSUE TITLE
Events to set volume level

### ISSUE THREAD

**Issue by c0r73x** [fulhax/ncpamixer#4]
Add new events for setting levels at certain percent.

For example:
set_volume_10 sets volume to 10%

**Comment by rendom** [comment]
#### Default config bindings:

| Event | Default | |
| --- | --- |---|
| 1 | set_volume_10 | Set volume to 10% on selected item |
| 2 | set_volume_20 | Set volume to 20% on selected item |
| 3 | set_volume_30 | Set volume to 30% on selected item |
| 4 | set_volume_40 | Set volume to 40% on selected item |
| 5 | set_volume_50 | Set volume to 50% on selected item |
| 6 | set_volume_60 | Set volume to 60% on selected item |
| 7 | set_volume_70 | Set volume to 70% on selected item |
| 8 | set_volume_80 | Set volume to 80% on selected item |
| 9 | set_volume_90 | Set volume to 90% on selected item |
| 0 | set_volume_0 | Set volume to 0% on selected item |

**Comment by c0r73x** [comment]
Probably better to use set_volume_100 for 0 since we already have mute.

**Comment by c0r73x** [comment]
Done, added both set_volume_0 and set_volume_100, but bound 0 to set_volume_0 and set_volume_100 is unbound.
