### ISSUE TITLE
NCPAMIXER controls not working on Manjaro i3

### ISSUE THREAD

**Issue by vinicius507** [fulhax/ncpamixer#41]
I'm running Manjaro i3 20.0.1. I installed pulseaudio and pavucontrol, which are working. But then, I saw a video about ncpamixer and installed it through AUR. Cloned the repository into my /tmp/ folder and used `makepkg -si` to install it. The only keybind working was L and H to navigate through tabs, nothing else.

**Comment by GregTheMadMonk** [comment]
I have the same problem on Arch with i3 on all terminals that I have (Alacritty, st, xfce4-terminal, xterm, urxvt).
By printing out the `event` value on `handleEvents(const char* event)` line-by-line it seems that after this line:
https://github.com/fulhax/ncpamixer/blob/8ab3a86cf048ae89c0c48f7f338ba0245bef5d99/src/ui/tab.cpp#L244
it value just changes to something obscure. It seems to be some magic I'm too dumb to understand. Changing function argument to `const std::string& s_event` and then initializing `event` as `s_event.c_str()` inside the function itself seems to fix everything, but doesn't fit the code style.

**Comment by kiowas** [comment]
I have the same problem on Arch with plasma on multiple terminals. The minimal fix is working for me.

**Comment by GregTheMadMonk** [comment]
Does fix work for everyone? Shouldn't this issue be closed now?
