### ISSUE TITLE
1.3.3.1 and master segfault, 1.3.3 is fine

### ISSUE THREAD

**Issue by dromer** [fulhax/ncpamixer#47]
with `1.3.3.1` or current `master` branch I just briefly see a message:
`Establishing connection to PulseAudio. Please wait...`

and then:
`Segmentation fault (core dumped)`

on `1.3.3` this does not happen, however I don't see the correct terminal fonts for the gui (as mentioned in #46 ).

**Comment by c0r73x** [comment]
I'm aware of this issue, I will fix it when i got some spare time.

**Comment by dromer** [comment]
Not sure if related, but I'm now trying to run ncpamixer on top of pipewire.
Latest master commit `2bf5ce61d217667a62dbed8cc7b5cb1da2d92d5f` segfaults after some time.
My terminal seems pretty F-ed after this so I couldn't copy/paste the details, here is a screenshot from gdb: https://i.imgur.com/F2viW2U.png

**Comment by samek-h** [comment]
Is this resolved 30aa766ef7ee85b65196ed48ce7637b9db2fb945?

**Comment by dromer** [comment]
Just built latest master `c6c1ad9c13c3f9639fa45b321a3a71e99da67321` and it seems to work alright (except I'm unable to switch tabs).
