### ISSUE TITLE
ncpamixer crashes when module-loopback is loaded

### ISSUE THREAD

**Issue by GregTheMadMonk** [fulhax/ncpamixer#48]
The title says it all (at least, all I could tell): when **module-loopback** is loaded, ncpamixer crashes. If you unload the module, it starts, but would crash once you have loaded it again.

**Comment by jakem72360** [comment]
Possibly related, ncpamixer crashes with a segfault if `module-equalizer-sink` is loaded, but works fine otherwise.

**Comment by GregTheMadMonk** [comment]
I think I've fixed it (see commit and #49). @jakem72360 can you test it on you side? Does it fix your problem?

**Comment by c0r73x** [comment]
Merged

**Comment by GregTheMadMonk** [comment]
Thanks! Hope it helps with other related issues too :)

**Comment by jakem72360** [comment]
@GregTheMadMonk works like a charm :)

**Comment by nick4f42** [comment]
I'm having this issue on version v1.3. If I start ncpamixer with module-loopback loaded or load it while ncpamixer is running, I get `segmentation fault (core dumped)`.

**Comment by c0r73x** [comment]
> 

1.3 dont have this fix, you must run 1.3.3.1 or higher

**Comment by nick4f42** [comment]
> 1.3 dont have this fix, you must run 1.3.3.1 or higher

Yep, I updated to 1.3.3.3 and it works now. Thanks
