### ISSUE TITLE
SIGSEGV When selecting new track in VLC

### ISSUE THREAD

**Issue by andrewathalye** [fulhax/ncpamixer#58]
pipewire-pulse: 0.3.44-r1/~amd64
ncpamixer: 1.3.3.1/~amd64
wireplumber: 0.4.7-r1/~amd64
vlc: 3.0.16-r7/amd64
Gentoo x86_64 nomultilib/systemd

When using this combination with a playlist of FLAC and MP3 files, ncpamixer crashes with a SIGSEGV upon selecting a new track. From what I can observe in pavucontrol, VLC destroys its connection to pulseaudio and recreates it whenever a new track is selected, which seems to crash ncpamixer. It does not crash pamix, however neither are able to smoothly display VLC's level bars, indicating maybe some sort of sample rate inconsistency. My FLAC files are standard 48khz, and my MP3s are mostly 384kbps 44.1khz. I unfortunately can't share any sample files, but some of them can be downloaded from Bungie's website for free if you have trouble reproducing this. 

I can also try building as debug, but I don't have much experience with gdb and probably wouldn't be able to make much in the way of a useful stacktrace.

**Comment by wael444** [comment]
can reproduce, but it happens when anything is new to ncpamixer.

eg. selecting a new song
