### ISSUE TITLE
ncpamixer segfaults when using non-existing "--help" parameter

### ISSUE THREAD

**Issue by SvenWe** [fulhax/ncpamixer#6]
I was just testing ncpamixer and was greeted with a segmentation fault when I ran it for the first time. I usually do run a `${command} --help` for any new software, just to see how to run the software properly.

<pre>
sven /portage > ncpamixer --help
zsh: segmentation fault  ncpamixer --help
sven /portage > ncpamixer -h    
ncpamixer: invalid option -- 'h'
(the command above starts ncpamixer)
sven /portage > ncpamixer -v
ncpamixer v
Build type: gentoo
Build date: 2016-08-17 13:23

sven /portage > ncpamixer --version
ncpamixer v
Build type: gentoo
Build date: 2016-08-17 13:23
</pre>

I guess there is a minor bug in the use of [`getopt_long()`](http://linux.die.net/man/3/getopt_long) and its `longOpts` parameter. The man page states:

> The last element of the array has to be filled with zeros. 

And the example has the following definition:

<pre>
        static struct option long_options[] = {
            {"add",     required_argument, 0,  0 },
            {"append",  no_argument,       0,  0 },
            {"delete",  required_argument, 0,  0 },
            {"verbose", no_argument,       0,  0 },
            {"create",  required_argument, 0, 'c'},
            {"file",    required_argument, 0,  0 },
            {0,         0,                 0,  0 }
        };
</pre>

I wrote a small patch which fixes the segmentation fault, and I'm going to create a pull request.

**Comment by rendom** [comment]
Merged into dev branch and it will be released in v1.1
