### ISSUE TITLE
Change mousewheel scroll behaviour on volumes from set to increment/decrement

### ISSUE THREAD

**Issue by Cubicuz** [fulhax/ncpamixer#69]
Hay all,
when i use the mouse wheel on a volume, the slider jumps to the position of the cursor.
I would rather expect it to increment/decrement the volume in this case.

If you would like to have this behavior feel free to look at/take my implementation at:
https://github.com/Cubicuz/ncpamixer/commit/b2d80b5b3af85a893966c45b6be178f50b93ccb3

Thanks in advance!

**Comment by c0r73x** [comment]
Makes sense 👍 merged

**Comment by Cubicuz** [comment]
thanks for the fast reply :smile:
