### ISSUE TITLE
Assertion 'c' failed at pulse/context.c:1055, function void pa_context_disconnect(pa_context *)(). Aborting.

### ISSUE THREAD

**Issue by yurivict** [fulhax/ncpamixer#74]
ncpamixer fails at runtime:

```
$ ncpamixer 
W: [(null)] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
Assertion 'c' failed at pulse/context.c:1055, function void pa_context_disconnect(pa_context *)(). Aborting.
Abort trap
```

Versions: 1.3.3.5, 1.3.4
pulseaudio-14.2
OS: FreeBSD 13.2

**Comment by c0r73x** [comment]
Seems your PulseAudio needs to be rebuilt with capabilities support? 🤔

`but that's impossible because PulseAudio was built without capabilities support`

**Comment by yurivict** [comment]
But is this what's really a problem for ncpamixer? Does it really require compatibilities support?

Because the previous versions worked w/out compatibilities support.

**Comment by c0r73x** [comment]
Seems to be the same issue as https://github.com/fulhax/ncpamixer/issues/61 I will close this one.
