### ISSUE TITLE
change default opening view

### ISSUE THREAD

**Issue by PhilT001** [fulhax/ncpamixer#77]
Not sure how to word this, is there an option to change what the default opening screen/view is from "Playback" to any of the other tabs? 

I'd like to have it set as "Output Devices" But an option to select "Recording" or "Input Devices"  as well would be good.

**Comment by c0r73x** [comment]
Should be quite easy to implement, I will look into it 👍14 okt. 2023 kl. 11:31 skrev PhilT001 ***@***.***>:﻿
Not sure how to word this, is there an option to change what the default opening screen/view is from "Playback" to any of the other tabs?
I'd like to have it set as "Output Devices" But an option to select "Recording" or "Input Devices"  as well would be good.

**Comment by PhilT001** [comment]
That would be great!

**Comment by tricktux** [comment]
@PhilT001 it's the man page:
![image](https://github.com/fulhax/ncpamixer/assets/5428479/706412b8-fd9e-4ade-8268-5bad5098ff37)

as well as in help:
![image](https://github.com/fulhax/ncpamixer/assets/5428479/8cff7873-2b63-486f-9bc9-7a47d5404201)

**Comment by PhilT001** [comment]
Ahh, thanks for finding that. I was expecting to find an option in the config file.

**Comment by c0r73x** [comment]
Oh, I forgot we had this xD
