### ISSUE TITLE
What keycodes are being used?

### ISSUE THREAD

**Issue by JustCauseWhyNot** [fulhax/ncpamixer#79]
If I use xev, or `showkey --keycodes` they give me different values. Ex Q reports 24, but in ncpamixe.conf `keycode.113` is q. I'm quite confused any help would greatly appreciated.

Thank you.

**Comment by c0r73x** [comment]
Hi, you specify the ascii code for the key. That’s why we have some special keys. Can’t quite remember why we built it like this but there was some reason 😅

**Comment by JustCauseWhyNot** [comment]
Thank you very much!
