### ISSUE TITLE
Add detailed instructions to compile.

### ISSUE THREAD

**Issue by TheSandman86** [fulhax/ncpamixer#9]
Please add detailed instructions about the compilation of ncpamixer in the README.md. I'm getting some errors when i try to compile it in my laptop with ubuntu, but i'm not sure if i did it correctly.

**Comment by denilsonsa** [comment]
sudo apt-get install libncursesw5-dev

Also remember to delete the `build/` directory before trying to build again. For some reason, cmake caches the library paths, so it will keep complaining even after you install it.

**Comment by rendom** [comment]
Can you paste your output/errors from `make`

**Comment by c0r73x** [comment]
You must have cmake, libpulse-dev and libncursesw5-dev. Then it should work by just running make (or make release) in the ncpamixer folder.

**Comment by TheSandman86** [comment]
Hi, thanks for all the responses. I did all the the things that you say, and now the error is different, i have installed the missing dependencies and deleted the build directory. When i execute "make" this is the output:
make
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Curses (missing:  CURSES_LIBRARY CURSES_INCLUDE_PATH) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Got version 1.1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mauricio/.git/ncpamixer/build/Linux/debug
Scanning dependencies of target ncpamixer
[  5%] Building CXX object CMakeFiles/ncpamixer.dir/pulsemixer.cpp.o
In file included from /home/mauricio/.git/ncpamixer/src/pulsemixer.cpp:9:0:
/home/mauricio/.git/ncpamixer/src/ui/ui.hpp:4:21: fatal error: ncurses.h: No such file or directory
compilation terminated.
CMakeFiles/ncpamixer.dir/build.make:62: recipe for target 'CMakeFiles/ncpamixer.dir/pulsemixer.cpp.o' failed
make[3]: *** [CMakeFiles/ncpamixer.dir/pulsemixer.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ncpamixer.dir/all' failed
make[2]: *** [CMakeFiles/ncpamixer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:39: recipe for target 'build' failed
make: *** [build] Error 2

Thanks in advance.

**Comment by c0r73x** [comment]
Hi, I got the same error in my ubuntu 14.04 docker. 

I will check why it fails to find ncurses later tonight.

**Comment by c0r73x** [comment]
Ok, I managed to compile.. It seems that you need both libncurses5-dev and libncursesw5-dev.

However cmake should have failed, because of that i will flag it as a bug.

**Comment by TheSandman86** [comment]
Thanks, i have installed libncurses5-dev and now i can compile. Only one question: i cannot install ncpamixer, is there any way to do it? Or do i have to manually add the binary to my $PATH to execute it?

**Comment by FredrikHson** [comment]
added a install target in 0660472
previously you could run sudo make -C ./build/Linux/<release/debug> install

**Comment by TheSandman86** [comment]
I tried again, with the added lines in the Makefile and this time i was able to execute "make" and "sudo make install" without any issues. Thank you.

**Comment by TheSandman86** [comment]
I've tested the new version in another machine and works like a charm. The only thing i could ask for is to add the option in the make file to execute "make uninstall" and remove the program.
Thanks.
